version: '3.7'

services:

  erdv2_dev:
    image: erdv2_dev
    container_name: erdv2_dev
    stdin_open: true
    tty: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      # map local to remote folder, exclude node_modules
      - '.:/app'
      - '/app/node_modules' 
    ports:
      - 3000:3000
      - 35729:35729 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

  nginx-erdv2:
    image: nginx:latest
    container_name: culligan_nginx-erdv2
    working_dir: /var/www
    restart: always
    ports: 
      - 80:80
    volumes:
      - ./build/:/var/www
      - .docker/conf/nginx/erdv2.conf:/etc/nginx/conf.d/default.conf